// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3x5NwqeZzL-FrRvkaE6FMQKH-R_t9u6U',
    appId: '1:614047117346:web:66ca89f58762b764a25a7b',
    messagingSenderId: '614047117346',
    projectId: 'auth-app-fddb3',
    authDomain: 'auth-app-fddb3.firebaseapp.com',
    databaseURL: 'https://auth-app-fddb3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auth-app-fddb3.firebasestorage.app',
    measurementId: 'G-KWHK06D3E6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQnAsMafaBl0OZ4zp6vfvYrZtjSstpjqs',
    appId: '1:614047117346:android:edcd17c1d6705baca25a7b',
    messagingSenderId: '614047117346',
    projectId: 'auth-app-fddb3',
    databaseURL: 'https://auth-app-fddb3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auth-app-fddb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQG0tyP7MvAhk7nwBAC0tgHD7AA0MkyNo',
    appId: '1:614047117346:ios:bc120bb3c1f1d314a25a7b',
    messagingSenderId: '614047117346',
    projectId: 'auth-app-fddb3',
    databaseURL: 'https://auth-app-fddb3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auth-app-fddb3.firebasestorage.app',
    iosClientId: '614047117346-doqmcgfehcam9ch16fnhs3mpvhchj9jn.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQG0tyP7MvAhk7nwBAC0tgHD7AA0MkyNo',
    appId: '1:614047117346:ios:bc120bb3c1f1d314a25a7b',
    messagingSenderId: '614047117346',
    projectId: 'auth-app-fddb3',
    databaseURL: 'https://auth-app-fddb3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auth-app-fddb3.firebasestorage.app',
    iosClientId: '614047117346-doqmcgfehcam9ch16fnhs3mpvhchj9jn.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3x5NwqeZzL-FrRvkaE6FMQKH-R_t9u6U',
    appId: '1:614047117346:web:c1594bb80b52e9a5a25a7b',
    messagingSenderId: '614047117346',
    projectId: 'auth-app-fddb3',
    authDomain: 'auth-app-fddb3.firebaseapp.com',
    databaseURL: 'https://auth-app-fddb3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auth-app-fddb3.firebasestorage.app',
    measurementId: 'G-W0S1ZNV6MW',
  );
}
